server:
  port: 8085

spring:
  application:
    name: EcommercePaymentService

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
