server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

# Auth Service Configuration
auth:
  service:
    url: http://localhost:8081
    internal-key: secret-internal-key-12345

# Product Service Configuration
product:
  service:
    url: http://localhost:8082

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true

# Logging
logging:
  level:
    com.prade.cart: DEBUG
