server:
  port: 8083

spring:
  application:
    name: EcommerceCartService

  datasource:
    url: jdbc:mysql://localhost:3306/cart_db
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
