server:
  port: 8081

spring:
  application:
    name: EcommerceAuthService

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
