server:
  port: 8086

spring:
  application:
    name: EcommerceReportService

  datasource:
    url: jdbc:mysql://localhost:3306/report_db
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
