server:
  port: 8084

spring:
  application:
    name: EcommerceOrdersService

  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
